site_name: Low Code Development for Production
site_description: >-
  How to integrate Low Code development into a production development pipeline
site_url: https://binnes.github.io/Node-RED-container-prod/
site_author: Brian Innes
repo_name: binnes/Node-RED-container-prod
repo_url: https://github.com/binnes/Node-RED-container-prod
theme:
    name: mkdocs
#    name: readthedocs
    highlightjs: true
    nav_style: dark
use_directory_urls: false
plugins:
  - search
  - with-pdf:
      cover_subtitle: using a DHT11/22 and NeoPixel RGB LED with data analysis on the IBM Cloud
markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
extra_css:
    - css/extra.css
    - css/pdf-print.css
nav:
  - Home: index.md
  - Part 1:
    - Source Control : Node-REDsourceControl/README.md
  - Part 2:
    - Packaging Applications : Packaging-Node-RED-apps-in-containers/README.md
  - Part 3:
    - Config from Environment : Node-RED-config-from-environment/README.md
