site_name: Low Code Development for Production
site_description: >-
  How to integrate Low Code development into a production development pipeline
site_url: https://binnes.github.io/Node-RED-container-prod/
site_author: Brian Innes
repo_name: binnes/Node-RED-container-prod
repo_url: https://github.com/binnes/Node-RED-container-prod
theme:
    name: material
use_directory_urls: false
plugins:
  - search
  - with-pdf:
      cover_subtitle: How to integrate Low Code development into a production development pipeline
      output_path: pdf/lowCodeDev.pdf
#      debug_html: true
#      verbose: true
markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
extra_css:
    - css/extra.css
    - css/pdf-print.css
nav:
  - Home: index.md
  - Source Control : Node-REDsourceControl/README.md
  - Packaging Applications : Packaging-Node-RED-apps-in-containers/README.md
  - Config from Environment : Node-RED-config-from-environment/README.md
google_analytics:
  - 'UA-172132667-1'
  - 'binnes.github.io/Node-RED-container-prod/'